apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fg1
  name: pyroscope-client
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: pyroscope-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pyroscope-client
    spec:
      containers:
      - image: sample.io/rb_sample:latest
        imagePullPolicy: Always
        name: pyroscope-client
        ports:
        - containerPort: 80